config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :boards do
    resources :tasks
  end
  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  name       :string
#  overview   :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#

class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 100 }
  validates :name, uniqueness: true

  validates :overview, presence: true
  validates :overview, uniqueness: true
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#

class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text
#  deadline   :date
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#

class Task < ApplicationRecord
    belongs_to :user
    belongs_to :board
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_one :profile, dependent: :destroy

  def prepare_profile
    profile || build_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    def index
      @boards = Board.all
    end

    def show
      @board = Board.find(params[:id])
      @tasks = @board.tasks
    end

    def new
      @board = current_user.boards.build
    end

    def create
      @board = current_user.boards.build(board_params)
      if @board.save
        redirect_to board_path(@board)
      else
        flash.now[:errow] = '保存に失敗しました'
        render new
      end
    end

    def edit
      @board = current_user.boards.find(params[:id])
    end

    def update
      @board = current_user.boards.find(params[:id])
      if @board.update(board_params)
        redirect_to board_path(@board), notice: '更新できました'
      else
        flash.now[:error] = '更新できませんでした'
      end
    end

    def destroy
      board = current_user.boards.find(params[:id])
      board.destroy!
      redirect_to boards_path
    end

    private
    def board_params
      params.require(:board).permit(:name, :overview)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = current_user.profile
  end

  def edit
    # if current_user.profile.present?
    #   @profile = current_user.profile
    # else
    #   @profile = current_user.build_profile
    # end
    # 上の表現から下の表現へ変更できる
    # @profile = current_user.profile || current_user.build_profile
    # 更にこの表現から下記の表現へ変更できる（user.rb）
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィール画像更新'
    else
      flash.now[:error] = '更新できませんでした'
      render 'edit'
    end
  end

  def destroy
  end

  private
  def profile_params
    params.require(:profile).permit(:avatar)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def show
        @task = Task.find(params[:id])
    end

    def new
        @task = current_user.tasks.build
    end

    def create
        @task = current_user.tasks.build(task_params)
        @task.board_id = params[:board_id]
        @task.save
        redirect_to board_path(params[:board_id])
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to board_path(params[:board_id])
        else
            flash.noe[:error] = ''
        end
    end

    def destroy
        task = Task.find(params[:id])
        board_id = task.board_id
        task.destroy!
        redirect_to board_path(board_id)
    end

    private
        def task_params
            params.require(:task).permit(
                :content,
                :deadline,
                :title)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
  = form_with(model: @board, url: board_path, method: 'put', local: true) do |f|
    .field
      %div
        = f.label :name, 'Name'
      %div
        = f.text_field :name
    .field
      %div
        = f.label :overview, 'Description'
      %div
        = f.text_field :overview, class: 'large'
      = f.submit 'Submit', class: 'actions_btn'

app/views/boards/index.html.haml
.container
  %h2 All Boards
  - @boards.each do |board|
    = link_to board_path(board), class: 'card' do
      .card_name
        = board.name
      .card_btn
        = image_tag 'doted.png'
      .card_overview
        = board.overview
      .card_user
        - if board.user.profile && board.user.profile.avatar
          = image_tag board.user.profile.avatar
        - else
          = image_tag 'damy-profile-img.png'
    = link_to '削除します', board_path(board), data: { method: 'delete'}
    = link_to '編集します', edit_board_path(board)
  = link_to new_board_path, class: 'card new' do
    %p + Add new board

app/views/boards/new.html.haml
.container
  %h2 New Board
  = form_with(model: @board, local: true) do |f|
    .field
      %div
        = f.label :name, 'Name'
      %div
        = f.text_field :name
    .field
      %div
        = f.label :overview, 'Description'
      %div
        = f.text_field :overview, class: 'large'
      = f.submit 'Submit', class: 'actions_btn'

app/views/boards/show.html.haml
.container
  - @tasks.each do |task|
    = link_to 'リンクだよ', board_task_path(task.board_id, task.id)
    -# - binding.pry
    .card
      .card_name
        = task.title
      .card_overview
        = task.content
      .card_user
        - if task.user.profile && task.user.profile.avatar
          = image_tag board.user.profile.avatar
        -else
          = image_tag 'damy-profile-img.png'
  = link_to new_board_task_path(@board), class: 'card new' do
    %p + Add new board

app/views/home/index.html.haml
%p aaa

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=devise-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      .header_logo Boards
      .header_btn
        - if user_signed_in?
          = link_to 'Logout', destroy_user_session_path, data: { method: 'delete' }
        - else
          = link_to 'Log in', new_user_session_path
    = yield

app/views/profiles/edit.html.haml
.container
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, '画像'
    %div
      = f.file_field :avatar
    = f.submit 'Submit', class: 'actions_btn'

app/views/profiles/show.html.haml
.container
  - if current_user.profile.avatar.attached?
    = image_tag current_user.profile.avatar
  - else
    %p aaa

app/views/tasks/edit.html.haml
.container
  = form_with(model: @task, url: board_task_path, method: 'put', local: true) do |f|
    .field
      %div
        = f.label :title, 'Title'
      %div
        = f.text_field :title
    .field
      %div
        = f.label :content, 'Content'
      %div
        = f.text_field :content
      = f.submit 'Submit', class: 'actions_btn'

app/views/tasks/new.html.haml
.container
  = form_with(model: @task, url: board_tasks_path, method: 'post', local: true) do |f|
    .field
      %div
        = f.label :title, 'Title'
      %div
        = f.text_field :title
    .field
      %div
        = f.label :content, 'Content'
      %div
        = f.text_field :content
      = f.submit 'Submit', class: 'actions_btn'

app/views/tasks/show.html.haml
.container
  .card
    .card_name
      = @task.title
    .card_overview
      = @task.content
    .card_user
      - if @task.user.profile && @task.user.profile.avatar
        = image_tag board.user.profile.avatar
      -else
        = image_tag 'damy-profile-img.png'
  = link_to '削除します',board_task_path(), data: { method: 'delete' }